#!/usr/bin/env python3
"""Add newly introduced English ARB keys to all locale files with translations."""

from __future__ import annotations

import json
from pathlib import Path

ARB_DIR = Path(__file__).resolve().parent.parent / "lib" / "l10n"
EN_PATH = ARB_DIR / "app_en.arb"

NEW_KEYS = {
    "visitActionTitle",
    "visitActionAudioTitle",
    "visitActionAudioSubtitle",
    "visitActionCaptureTitle",
    "visitActionCaptureSubtitle",
    "inviteCaregiverDialogTitle",
    "caregiverNameHint",
    "caregiverEmailHint",
    "relationshipLabel",
    "relationshipHint",
    "sendInvite",
    "emailAndRoleRequired",
    "summaryReadyTitle",
    "summaryReadyBody",
    "later",
    "viewSummary",
    "noLabResultsYet",
    "labResultsScanHint",
    "captureAndScan",
    "noScannedDocsYet",
    "scannedDocsHint",
    "selectAtLeastOneSummary",
    "failedToDeleteSummaries",
    "noCaregiverAddedYet",
    "summaryGenerationRestarted",
    "retryFailed",
}

TRANSLATIONS: dict[str, dict[str, str]] = {
    "es": {
        "visitActionTitle": "¿Qué te gustaría hacer?",
        "visitActionAudioTitle": "Grabar conversación de audio",
        "visitActionAudioSubtitle": "Graba tu visita médica para obtener un resumen automático",
        "visitActionCaptureTitle": "Capturar y escanear",
        "visitActionCaptureSubtitle": "Toma fotos de informes, frascos de pastillas y documentos",
        "inviteCaregiverDialogTitle": "Invitar cuidador",
        "caregiverNameHint": "Ingresa el nombre completo del cuidador",
        "caregiverEmailHint": "Ingresa el correo del cuidador",
        "relationshipLabel": "Relación",
        "relationshipHint": "p. ej., Hijo, Hija, Amigo, Enfermera",
        "sendInvite": "Enviar invitación",
        "emailAndRoleRequired": "El correo y el rol son obligatorios",
        "summaryReadyTitle": "¡Tu resumen de visita está listo!",
        "summaryReadyBody": "¿Te gustaría verlo ahora?",
        "later": "Más tarde",
        "viewSummary": "Ver resumen",
        "noLabResultsYet": "Aún no hay resultados de laboratorio",
        "labResultsScanHint": "Escanea un informe de laboratorio con Capturar y escanear para ver los resultados aquí.",
        "captureAndScan": "Capturar y escanear",
        "noScannedDocsYet": "Aún no hay documentos escaneados",
        "scannedDocsHint": "Los documentos escaneados durante tus visitas aparecerán aquí.",
        "selectAtLeastOneSummary": "Selecciona al menos un resumen",
        "failedToDeleteSummaries": "No se pudieron eliminar los resúmenes. Inténtalo de nuevo.",
        "noCaregiverAddedYet": "Aún no se ha agregado un cuidador",
        "summaryGenerationRestarted": "La generación del resumen se reinició",
        "retryFailed": "Reintento fallido: {error}",
    },
    "hi": {
        "visitActionTitle": "आप क्या करना चाहेंगे?",
        "visitActionAudioTitle": "ऑडियो बातचीत रिकॉर्ड करें",
        "visitActionAudioSubtitle": "स्वचालित सारांश के लिए अपनी डॉक्टर विज़िट रिकॉर्ड करें",
        "visitActionCaptureTitle": "कैप्चर और स्कैन",
        "visitActionCaptureSubtitle": "रिपोर्ट, दवा की बोतलों और दस्तावेज़ों की तस्वीरें लें",
        "inviteCaregiverDialogTitle": "केयरगिवर को आमंत्रित करें",
        "caregiverNameHint": "केयरगिवर का पूरा नाम दर्ज करें",
        "caregiverEmailHint": "केयरगिवर का ईमेल पता दर्ज करें",
        "relationshipLabel": "संबंध",
        "relationshipHint": "जैसे, बेटा, बेटी, मित्र, नर्स",
        "sendInvite": "आमंत्रण भेजें",
        "emailAndRoleRequired": "ईमेल और भूमिका आवश्यक हैं",
        "summaryReadyTitle": "आपका विज़िट सारांश तैयार है!",
        "summaryReadyBody": "क्या आप इसे अभी देखना चाहेंगे?",
        "later": "बाद में",
        "viewSummary": "सारांश देखें",
        "noLabResultsYet": "अभी तक कोई लैब परिणाम नहीं",
        "labResultsScanHint": "यहाँ परिणाम देखने के लिए कैप्चर और स्कैन से लैब रिपोर्ट स्कैन करें।",
        "captureAndScan": "कैप्चर और स्कैन",
        "noScannedDocsYet": "अभी तक कोई स्कैन किए गए दस्तावेज़ नहीं",
        "scannedDocsHint": "आपकी विज़िट के दौरान स्कैन किए गए दस्तावेज़ यहाँ दिखाई देंगे।",
        "selectAtLeastOneSummary": "कम से कम एक सारांश चुनें",
        "failedToDeleteSummaries": "सारांश हटाने में विफल। कृपया पुनः प्रयास करें।",
        "noCaregiverAddedYet": "अभी तक कोई केयरगिवर नहीं जोड़ा गया",
        "summaryGenerationRestarted": "सारांश जनरेशन पुनः शुरू हुआ",
        "retryFailed": "पुनः प्रयास विफल: {error}",
    },
    "fr": {
        "visitActionTitle": "Que souhaitez-vous faire ?",
        "visitActionAudioTitle": "Enregistrer une conversation audio",
        "visitActionAudioSubtitle": "Enregistrez votre visite médicale pour un résumé automatique",
        "visitActionCaptureTitle": "Capturer et numériser",
        "visitActionCaptureSubtitle": "Prenez des photos de rapports, flacons de médicaments et documents",
        "inviteCaregiverDialogTitle": "Inviter un aidant",
        "caregiverNameHint": "Entrez le nom complet de l'aidant",
        "caregiverEmailHint": "Entrez l'adresse e-mail de l'aidant",
        "relationshipLabel": "Relation",
        "relationshipHint": "ex. : Fils, Fille, Ami, Infirmière",
        "sendInvite": "Envoyer l'invitation",
        "emailAndRoleRequired": "L'e-mail et le rôle sont requis",
        "summaryReadyTitle": "Votre résumé de visite est prêt !",
        "summaryReadyBody": "Souhaitez-vous le consulter maintenant ?",
        "later": "Plus tard",
        "viewSummary": "Voir le résumé",
        "noLabResultsYet": "Pas encore de résultats de laboratoire",
        "labResultsScanHint": "Numérisez un rapport de laboratoire avec Capturer et numériser pour voir les résultats ici.",
        "captureAndScan": "Capturer et numériser",
        "noScannedDocsYet": "Pas encore de documents numérisés",
        "scannedDocsHint": "Les documents numérisés lors de vos visites apparaîtront ici.",
        "selectAtLeastOneSummary": "Sélectionnez au moins un résumé",
        "failedToDeleteSummaries": "Échec de la suppression des résumés. Veuillez réessayer.",
        "noCaregiverAddedYet": "Aucun aidant ajouté pour le moment",
        "summaryGenerationRestarted": "La génération du résumé a redémarré",
        "retryFailed": "Nouvelle tentative échouée : {error}",
    },
    "pt": {
        "visitActionTitle": "O que você gostaria de fazer?",
        "visitActionAudioTitle": "Gravar conversa em áudio",
        "visitActionAudioSubtitle": "Grave sua consulta médica para um resumo automático",
        "visitActionCaptureTitle": "Capturar e digitalizar",
        "visitActionCaptureSubtitle": "Tire fotos de relatórios, frascos de remédios e documentos",
        "inviteCaregiverDialogTitle": "Convidar cuidador",
        "caregiverNameHint": "Digite o nome completo do cuidador",
        "caregiverEmailHint": "Digite o e-mail do cuidador",
        "relationshipLabel": "Relacionamento",
        "relationshipHint": "ex.: Filho, Filha, Amigo, Enfermeira",
        "sendInvite": "Enviar convite",
        "emailAndRoleRequired": "E-mail e função são obrigatórios",
        "summaryReadyTitle": "Seu resumo da visita está pronto!",
        "summaryReadyBody": "Gostaria de visualizá-lo agora?",
        "later": "Mais tarde",
        "viewSummary": "Ver resumo",
        "noLabResultsYet": "Ainda não há resultados de laboratório",
        "labResultsScanHint": "Digitalize um relatório de laboratório com Capturar e digitalizar para ver os resultados aqui.",
        "captureAndScan": "Capturar e digitalizar",
        "noScannedDocsYet": "Ainda não há documentos digitalizados",
        "scannedDocsHint": "Documentos digitalizados durante suas visitas aparecerão aqui.",
        "selectAtLeastOneSummary": "Selecione pelo menos um resumo",
        "failedToDeleteSummaries": "Falha ao excluir resumos. Tente novamente.",
        "noCaregiverAddedYet": "Nenhum cuidador adicionado ainda",
        "summaryGenerationRestarted": "A geração do resumo foi reiniciada",
        "retryFailed": "Nova tentativa falhou: {error}",
    },
    "de": {
        "visitActionTitle": "Was möchten Sie tun?",
        "visitActionAudioTitle": "Gespräch als Audio aufnehmen",
        "visitActionAudioSubtitle": "Nehmen Sie Ihren Arztbesuch für eine automatische Zusammenfassung auf",
        "visitActionCaptureTitle": "Erfassen und scannen",
        "visitActionCaptureSubtitle": "Fotografieren Sie Berichte, Medikamentenflaschen und Dokumente",
        "inviteCaregiverDialogTitle": "Betreuer einladen",
        "caregiverNameHint": "Vollständigen Namen des Betreuers eingeben",
        "caregiverEmailHint": "E-Mail-Adresse des Betreuers eingeben",
        "relationshipLabel": "Beziehung",
        "relationshipHint": "z. B. Sohn, Tochter, Freund, Krankenschwester",
        "sendInvite": "Einladung senden",
        "emailAndRoleRequired": "E-Mail und Rolle sind erforderlich",
        "summaryReadyTitle": "Ihre Besuchszusammenfassung ist fertig!",
        "summaryReadyBody": "Möchten Sie sie jetzt ansehen?",
        "later": "Später",
        "viewSummary": "Zusammenfassung anzeigen",
        "noLabResultsYet": "Noch keine Laborergebnisse",
        "labResultsScanHint": "Scannen Sie einen Laborbericht mit Erfassen und scannen, um die Ergebnisse hier zu sehen.",
        "captureAndScan": "Erfassen und scannen",
        "noScannedDocsYet": "Noch keine gescannten Dokumente",
        "scannedDocsHint": "Während Ihrer Besuche gescannte Dokumente erscheinen hier.",
        "selectAtLeastOneSummary": "Wählen Sie mindestens eine Zusammenfassung aus",
        "failedToDeleteSummaries": "Zusammenfassungen konnten nicht gelöscht werden. Bitte erneut versuchen.",
        "noCaregiverAddedYet": "Noch kein Betreuer hinzugefügt",
        "summaryGenerationRestarted": "Zusammenfassungserstellung neu gestartet",
        "retryFailed": "Wiederholung fehlgeschlagen: {error}",
    },
    "bn": {
        "visitActionTitle": "আপনি কী করতে চান?",
        "visitActionAudioTitle": "অডিও কথোপকথন রেকর্ড করুন",
        "visitActionAudioSubtitle": "স্বয়ংক্রিয় সারাংশের জন্য আপনার ডাক্তারের ভিজিট রেকর্ড করুন",
        "visitActionCaptureTitle": "ক্যাপচার ও স্ক্যান",
        "visitActionCaptureSubtitle": "রিপোর্ট, ওষুধের বোতল ও নথির ছবি তুলুন",
        "inviteCaregiverDialogTitle": "যত্নকারীকে আমন্ত্রণ",
        "caregiverNameHint": "যত্নকারীর পুরো নাম লিখুন",
        "caregiverEmailHint": "যত্নকারীর ইমেইল ঠিকানা লিখুন",
        "relationshipLabel": "সম্পর্ক",
        "relationshipHint": "যেমন, ছেলে, মেয়ে, বন্ধু, নার্স",
        "sendInvite": "আমন্ত্রণ পাঠান",
        "emailAndRoleRequired": "ইমেইল ও ভূমিকা প্রয়োজন",
        "summaryReadyTitle": "আপনার ভিজিট সারাংশ প্রস্তুত!",
        "summaryReadyBody": "আপনি কি এখনই দেখতে চান?",
        "later": "পরে",
        "viewSummary": "সারাংশ দেখুন",
        "noLabResultsYet": "এখনও কোনো ল্যাব ফলাফল নেই",
        "labResultsScanHint": "এখানে ফলাফল দেখতে ক্যাপচার ও স্ক্যান দিয়ে ল্যাব রিপোর্ট স্ক্যান করুন।",
        "captureAndScan": "ক্যাপচার ও স্ক্যান",
        "noScannedDocsYet": "এখনও কোনো স্ক্যান করা নথি নেই",
        "scannedDocsHint": "আপনার ভিজিটের সময় স্ক্যান করা নথি এখানে দেখা যাবে।",
        "selectAtLeastOneSummary": "অন্তত একটি সারাংশ নির্বাচন করুন",
        "failedToDeleteSummaries": "সারাংশ মুছতে ব্যর্থ। আবার চেষ্টা করুন।",
        "noCaregiverAddedYet": "এখনও কোনো যত্নকারী যোগ করা হয়নি",
        "summaryGenerationRestarted": "সারাংশ তৈরি পুনরায় শুরু হয়েছে",
        "retryFailed": "পুনরায় চেষ্টা ব্যর্থ: {error}",
    },
    "ta": {
        "visitActionTitle": "நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?",
        "visitActionAudioTitle": "ஆடியோ உரையாடலை பதிவு செய்",
        "visitActionAudioSubtitle": "தானியங்கி சுருக்கத்திற்கு உங்கள் மருத்துவர் வருகையை பதிவு செய்யுங்கள்",
        "visitActionCaptureTitle": "பிடித்து ஸ்கேன் செய்",
        "visitActionCaptureSubtitle": "அறிக்கைகள், மருந்து பாட்டில்கள் மற்றும் ஆவணங்களின் புகைப்படங்களை எடுக்கவும்",
        "inviteCaregiverDialogTitle": "பராமரிப்பாளரை அழை",
        "caregiverNameHint": "பராமரிப்பாளரின் முழு பெயரை உள்ளிடவும்",
        "caregiverEmailHint": "பராமரிப்பாளரின் மின்னஞ்சலை உள்ளிடவும்",
        "relationshipLabel": "உறவு",
        "relationshipHint": "எ.கா., மகன், மகள், நண்பர், செவிலியர்",
        "sendInvite": "அழைப்பு அனுப்பு",
        "emailAndRoleRequired": "மின்னஞ்சல் மற்றும் பாத்திரம் தேவை",
        "summaryReadyTitle": "உங்கள் வருகை சுருக்கம் தயார்!",
        "summaryReadyBody": "இப்போது பார்க்க விரும்புகிறீர்களா?",
        "later": "பின்னர்",
        "viewSummary": "சுருக்கத்தைப் பார்",
        "noLabResultsYet": "இன்னும் ஆய்வக முடிவுகள் இல்லை",
        "labResultsScanHint": "முடிவுகளை இங்கே பார்க்க பிடித்து ஸ்கேன் மூலம் ஆய்வக அறிக்கையை ஸ்கேன் செய்யுங்கள்.",
        "captureAndScan": "பிடித்து ஸ்கேன் செய்",
        "noScannedDocsYet": "இன்னும் ஸ்கேன் செய்யப்பட்ட ஆவணங்கள் இல்லை",
        "scannedDocsHint": "உங்கள் வருகைகளின் போது ஸ்கேன் செய்யப்பட்ட ஆவணங்கள் இங்கே தோன்றும்.",
        "selectAtLeastOneSummary": "குறைந்தது ஒரு சுருக்கத்தைத் தேர்ந்தெடுக்கவும்",
        "failedToDeleteSummaries": "சுருக்கங்களை நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
        "noCaregiverAddedYet": "இன்னும் பராமரிப்பாளர் சேர்க்கப்படவில்லை",
        "summaryGenerationRestarted": "சுருக்க உருவாக்கம் மீண்டும் தொடங்கியது",
        "retryFailed": "மீண்டும் முயற்சி தோல்வி: {error}",
    },
    "gu": {
        "visitActionTitle": "તમે શું કરવા માંગો છો?",
        "visitActionAudioTitle": "ઑડિયો વાતચીત રેકોર્ડ કરો",
        "visitActionAudioSubtitle": "સ્વચાલિત સારાંશ માટે તમારી ડૉક્ટરની મુલાકાત રેકોર્ડ કરો",
        "visitActionCaptureTitle": "કેપ્ચર અને સ્કેન",
        "visitActionCaptureSubtitle": "રિપોર્ટ, દવાની બોટલો અને દસ્તાવેજોની ફોટો લો",
        "inviteCaregiverDialogTitle": "સંભાળ રાખનારને આમંત્રિત કરો",
        "caregiverNameHint": "સંભાળ રાખનારનું પૂરું નામ દાખલ કરો",
        "caregiverEmailHint": "સંભાળ રાખનારનું ઇમેઇલ સરનામું દાખલ કરો",
        "relationshipLabel": "સંબંધ",
        "relationshipHint": "દા.ત., પુત્ર, પુત્રી, મિત્ર, નર્સ",
        "sendInvite": "આમંત્રણ મોકલો",
        "emailAndRoleRequired": "ઇમેઇલ અને ભૂમિકા જરૂરી છે",
        "summaryReadyTitle": "તમારો મુલાકાત સારાંશ તૈયાર છે!",
        "summaryReadyBody": "શું તમે તે હમણાં જોવા માંગો છો?",
        "later": "પછી",
        "viewSummary": "સારાંશ જુઓ",
        "noLabResultsYet": "હજી સુધી કોઈ લેબ પરિણામો નથી",
        "labResultsScanHint": "પરિણામો અહીં જોવા કેપ્ચર અને સ્કેનથી લેબ રિપોર્ટ સ્કેન કરો.",
        "captureAndScan": "કેપ્ચર અને સ્કેન",
        "noScannedDocsYet": "હજી સુધી કોઈ સ્કેન કરેલા દસ્તાવેજો નથી",
        "scannedDocsHint": "તમારી મુલાકાતો દરમિયાન સ્કેન કરેલા દસ્તાવેજો અહીં દેખાશે.",
        "selectAtLeastOneSummary": "ઓછામાં ઓછું એક સારાંશ પસંદ કરો",
        "failedToDeleteSummaries": "સારાંશો કાઢી શકાયા નહીં. કૃપા કરીને ફરી પ્રયાસ કરો.",
        "noCaregiverAddedYet": "હજી સુધી કોઈ સંભાળ રાખનાર ઉમેરાયો નથી",
        "summaryGenerationRestarted": "સારાંશ જનરેશન ફરી શરૂ થયું",
        "retryFailed": "પુનઃપ્રયાસ નિષ્ફળ: {error}",
    },
    "pa": {
        "visitActionTitle": "ਤੁਸੀਂ ਕੀ ਕਰਨਾ ਚਾਹੋਗੇ?",
        "visitActionAudioTitle": "ਆਡੀਓ ਗੱਲਬਾਤ ਰਿਕਾਰਡ ਕਰੋ",
        "visitActionAudioSubtitle": "ਸਵੈਚਾਲਿਤ ਸਾਰਾਂਸ਼ ਲਈ ਆਪਣੀ ਡਾਕਟਰ ਮੁਲਾਕਾਤ ਰਿਕਾਰਡ ਕਰੋ",
        "visitActionCaptureTitle": "ਕੈਪਚਰ ਅਤੇ ਸਕੈਨ",
        "visitActionCaptureSubtitle": "ਰਿਪੋਰਟਾਂ, ਦਵਾਈ ਦੀਆਂ ਬੋਤਲਾਂ ਅਤੇ ਦਸਤਾਵੇਜ਼ਾਂ ਦੀਆਂ ਫੋਟੋਆਂ ਲਓ",
        "inviteCaregiverDialogTitle": "ਦੇਖਭਾਲ ਕਰਨ ਵਾਲੇ ਨੂੰ ਸੱਦਾ ਦਿਓ",
        "caregiverNameHint": "ਦੇਖਭਾਲ ਕਰਨ ਵਾਲੇ ਦਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ",
        "caregiverEmailHint": "ਦੇਖਭਾਲ ਕਰਨ ਵਾਲੇ ਦਾ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ",
        "relationshipLabel": "ਰਿਸ਼ਤਾ",
        "relationshipHint": "ਜਿਵੇਂ, ਪੁੱਤਰ, ਧੀ, ਦੋਸਤ, ਨਰਸ",
        "sendInvite": "ਸੱਦਾ ਭੇਜੋ",
        "emailAndRoleRequired": "ਈਮੇਲ ਅਤੇ ਭੂਮਿਕਾ ਲੋੜੀਂਦੀ ਹੈ",
        "summaryReadyTitle": "ਤੁਹਾਡਾ ਮੁਲਾਕਾਤ ਸਾਰਾਂਸ਼ ਤਿਆਰ ਹੈ!",
        "summaryReadyBody": "ਕੀ ਤੁਸੀਂ ਇਸਨੂੰ ਹੁਣੇ ਦੇਖਣਾ ਚਾਹੋਗੇ?",
        "later": "ਬਾਅਦ ਵਿੱਚ",
        "viewSummary": "ਸਾਰਾਂਸ਼ ਦੇਖੋ",
        "noLabResultsYet": "ਅਜੇ ਤੱਕ ਕੋਈ ਲੈਬ ਨਤੀਜੇ ਨਹੀਂ",
        "labResultsScanHint": "ਨਤੀਜੇ ਇੱਥੇ ਦੇਖਣ ਲਈ ਕੈਪਚਰ ਅਤੇ ਸਕੈਨ ਨਾਲ ਲੈਬ ਰਿਪੋਰਟ ਸਕੈਨ ਕਰੋ।",
        "captureAndScan": "ਕੈਪਚਰ ਅਤੇ ਸਕੈਨ",
        "noScannedDocsYet": "ਅਜੇ ਤੱਕ ਕੋਈ ਸਕੈਨ ਕੀਤੇ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ",
        "scannedDocsHint": "ਤੁਹਾਡੀਆਂ ਮੁਲਾਕਾਤਾਂ ਦੌਰਾਨ ਸਕੈਨ ਕੀਤੇ ਦਸਤਾਵੇਜ਼ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।",
        "selectAtLeastOneSummary": "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਸਾਰਾਂਸ਼ ਚੁਣੋ",
        "failedToDeleteSummaries": "ਸਾਰਾਂਸ਼ ਮਿਟਾਉਣ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
        "noCaregiverAddedYet": "ਅਜੇ ਤੱਕ ਕੋਈ ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਾ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ",
        "summaryGenerationRestarted": "ਸਾਰਾਂਸ਼ ਜਨਰੇਸ਼ਨ ਮੁੜ ਸ਼ੁਰੂ ਹੋਈ",
        "retryFailed": "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਅਸਫਲ: {error}",
    },
}


def main() -> None:
    en = json.loads(EN_PATH.read_text(encoding="utf-8"))
    for path in sorted(ARB_DIR.glob("app_*.arb")):
        if path.name == "app_en.arb":
            continue
        code = path.stem.replace("app_", "")
        loc = json.loads(path.read_text(encoding="utf-8"))
        translations = TRANSLATIONS.get(code, {})
        added = 0
        for key in NEW_KEYS:
            if key in loc:
                continue
            value = translations.get(key) or en[key]
            loc[key] = value
            meta_key = f"@{key}"
            if meta_key in en and meta_key not in loc:
                loc[meta_key] = en[meta_key]
            added += 1
        path.write_text(
            json.dumps(loc, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"{path.name}: added {added} keys")


if __name__ == "__main__":
    main()
