package com.remiminderai.app

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

/**
 * Exposes the Firebase/Google Services Web client ID to Flutter so
 * GoogleSignIn.serverClientId always matches google-services.json.
 */
class MainActivity : FlutterActivity() {
    private val channelName = "com.remiminderai.app/google_auth"

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, channelName)
            .setMethodCallHandler { call, result ->
                when (call.method) {
                    "getWebClientId" -> {
                        val webClientId = try {
                            // default_web_client_id is generated by the Google Services plugin
                            val resId = resources.getIdentifier(
                                "default_web_client_id",
                                "string",
                                packageName
                            )
                            if (resId != 0) getString(resId) else null
                        } catch (_: Exception) {
                            null
                        }
                        result.success(webClientId)
                    }
                    else -> result.notImplemented()
                }
            }
    }
}
